version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "pre-commit"
      - dependency-name: "pytest"
      - dependency-name: "pytest-cov"
      - dependency-name: "ruff"
    commit-message:
      prefix: â¬†
    labels:
      - "dependencies"
